#
# Copyright 2011-2021 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

all:
	
	@make -s --no-print-directory build -C Carousel
	@make -s --no-print-directory build -C Doom
	@make -s --no-print-directory build -C Descent

rebuild:
	
	@make -s --no-print-directory rebuild -C Carousel
	@make -s --no-print-directory rebuild -C Doom
	@make -s --no-print-directory rebuild -C Descent

rebuild-embedded:

	@make -s --no-print-directory rebuild -C Engine